# for taint use kubectl taint nodes node-id value=something:NoSchedule
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    company: wipro
    employee: dev
spec: 
  replicas: 3 # deployment defination starts from here
  selector:
    matchLabels:
      company: wipro
      employee: dev
  template: # pod defination start from here
    metadata:
      labels:
        company: wipro
        employee: dev
    spec:
      nodeSelector: # need to provide node selector also bcz it may or may not be schedule to this node
        topology.kubernetes.io/zone: us-east-1d
      containers:
        - name: nginx
          image: nginx
          key: "project"
          value: "roboshop"
          operator: "Equal"
          effect: "NoSchedule"
