apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessMode:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # retain means don't delete data, Recycle means delete data but don't delete disk, Delete means delete the disk.
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-07917368aed59a770