# this storage class should be create by k8s admin team
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-01
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-01
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    ebs: ebs-dynamic
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share//nginx/html
  nodeSelector: # without nodeselector it may assign to other node which are in other availability zone then it gets faile
    topology.ebs.csi.aws.com/zone: us-east-1b ## it should be same in 1b only we have to take
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: claim1 # PersistentVolume Claim name we have to use here to claim
---
apiVersion: v1
kind: Service
metadata: 
  name: service-01
spec:
  type: LoadBalancer
  selector:
    ebs: ebs-dynamic
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      nodePort: 30007
