# this storage class should be create by k8s admin team
# note : this is EBS dynamic provisioning, this we are not creating pv and pvc and mount point of aws separatly we are creating storageclass and we are using that with persistenvolumeclaim option and we don't require to mentione node-selector it will only checks and adds storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-01
reclaimPolicy: Retain # retain means don't delete data,
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer # whenever pod is creating that only one it allocate storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-01
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    ebs: ebs-dynamic
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share//nginx/html
# node selector not required for dynamic ebs storage.
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: claim1 # PersistentVolume Claim name we have to use here to claim
---
apiVersion: v1
kind: Service
metadata: 
  name: service-01
spec:
  type: LoadBalancer
  selector:
    ebs: ebs-dynamic
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      nodePort: 30007
