apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # retain means don't delete data, Recycle means delete data but don't delete disk, Delete means delete the disk.
  capacity:
    storage: 5Gi # its for dummy, actual size is elastic
  storageClassName: "" # should be emptyin static
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-07e09f1ac3abd586b # need to paste efs volume id
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  storageClassName: "" 
  volumeName: efs-static # pv name and this should be same
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    ebs: ebs-static
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: efs-static # and pvc name should be same
---
apiVersion: v1
kind: Service
metadata: 
  name: service-01
spec:
  type: LoadBalancer
  selector:
    ebs: ebs-static
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      nodePort: 30007

