apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes: 
    - ReadWriteMany
  storageClassName: roboshop-efs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    ebs: efs-dynamic
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
# node selector not required for dynamic ebs storage.
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: efs-dynamic # PersistentVolume Claim name we have to use here to claim
