apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: apache-pvc
spec:
  accessModes:  
    - ReadWriteMany
  storageClassName: efs-demo
  resources:
    storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-demo
  resources:
    storage: 5Gi