# storage class for dynamic efs
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-demo
reclaimPolicy: Retain # retain means don't delete data,
provisioner: efs.csi.aws.com # working with efs driver
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-065f1e20bcc5b96cc # file system id
  directoryPerms: "700"
  basePath: "/roboshop" # optional
--- # pvc creation and taking storage class name for apache
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: apache-pvc
spec:
  accessModes:  
    - ReadWriteMany
  storageClassName: efs-demo
  resources:
    requests:
      storage: 5Gi
--- # pvc creation and taking storage class name for tomcat
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-demo
  resources:
    requests:
      storage: 5Gi
--- # creating pod using pvc for apache we can check at access point
apiVersion: v1
kind: Pod
metadata:
  name: apache-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: apache-pvc # PersistentVolume Claim name we have to use here to claim
--- # creating pod using pvc for apache we can check at access point
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: tomcat-pvc # PersistentVolume Claim name we have to use here to claim

