apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  labels:
    purpose: k2
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: k2
  template:
    metadata:
      labels:
        purpose: k2
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    purpose: k2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-headless
# spec:
#   clusterIP: None # this is called headless service
#   selector:
#     purpose: k2
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80