apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  serviceAccount: app-sa
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["sleep", "3600"]
    # - name: nginx
    #   image: nginx
