# enable OIDC driver onetime eksctl utils associate-iam-oidc-provider --region us-east-1 --cluster Test12345 --approve
# verify aws eks describe-cluster --name <cluster-name> --query "cluster.identity.oidc.issuer"

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default
