# enable OIDC driver onetime -- eksctl utils associate-iam-oidc-provider --region us-east-1 --cluster Test12345 --approve
#  aws eks describe-cluster --name Test12345 --query "cluster.identity.oidc.issuer" --output text
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::683134746681:role/kiran-test-role # role arn we have to give that role also should be attache to policy and that policy to attach to oidc of identity providers