apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::683134746681:role/eksctl-Test12345-nodegroup-robosho-NodeInstanceRole-zng526tR1CJx
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
  - rolearn: arn:aws:iam::<account-id>:role/eks-suresh-role
    username: suresh
    groups:
      - trainees
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-28T16:26:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1119"
  uid: 7b7db883-daa4-4502-8585-1dab8966c6e8

  # instead edit config map kubectl edit configmap aws-auth -n kube-system
  # mapRoles: |
  # - rolearn: arn:aws:iam::<account-id>:role/eks-suresh-role
  #   username: suresh
  #   groups:
  #     - trainees


# sudo apt install awscli -y
# curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
# chmod +x kubectl
# sudo mv kubectl /usr/local/bin/

#aws eks update-kubeconfig --region <region> --name Test12345

# kubectl auth can-i watch pods

# kubectl get pods
# kubectl get pods --watch

# 1 Steps create user in aws with policy in that select for eks read> describe pod
# 2 create role in 01 for role trainee then rolebinding 02 bind trainee to suresh user
# 3 take kubectl get configmap aws-auth -n kube-system -o yaml and add content of mapUsers and apply it kubectl apply -f again. 
# 4 launch on aws instance install kubectl then create security credentials for suresh user then do aws configure in newly launched install with region the run update aws configure
# 5 aws eks update-kubeconfig --region us-east-1 --name Test12345