apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::683134746681:role/eksctl-Test12345-nodegroup-robosho-NodeInstanceRole-zng526tR1CJx
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - trainee
      userarn: arn:aws:iam::683134746681:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-28T16:26:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1119"
  uid: 7b7db883-daa4-4502-8585-1dab8966c6e8